spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessRecommendation
      database: fitnessRecommendation
    rabbitmq:
      host: localhost
      port: 5672
      username: ${RABBITMQ_USERNAME}
      password: ${RABBITMQ_PASSWORD}
  ai:
    mistralai:
      api-key: ${MISTRALAI_API_KEY}
      base-url: https://api.mistral.ai/v1/chat/completions


server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

logging:
  level:
    org.springframework.boot.autoconfigure.mongo: DEBUG
    org.springframework.data.mongodb.core: DEBUG